spring.application.name=viaggi
spring.config.import=file:src/main/resources/env.properties
server.port=${PORT}

# DB CONFIG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
cloudinary.name=${CLOUDINARY_NAME}
